<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXh1tirh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXh1tirh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXh1tirh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXh1tirh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXh1tirh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xh1tirh',
    'container.build_id' => '062da6f0',
    'container.build_time' => 1638177199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXh1tirh');
